export interface IHeritage {
    id: number;
    name: string;
    registrationDistrict: string;
    registrationYear: string;
    province: string;
    typeofProject: string;
    batchNo: string;
    inheritors: string;
    projectOverview: string;
    history: string;
    currentStatus: string;
    presentValue: number;
    endangeredStatus: string;
    masterpiece: string;
    tourismStatus: string;
    tourismMarketCharacteristics: string;
    tourismProduct: string;
    tourismPrice: number;
    tourismDevelopmentModel: string;
    tourismBenefit: number;
    story: string; 
    createdUserId: number;
    createdUserName: string;
    createdOn: Date;
    modifiedUserId: number;
    modifiedUserName: string;
    modifiedOn: Date;
}